### ISSUE TITLE
Top bar not persistant

### ISSUE THREAD

**Issue by 287mdsahil** [JuDivideAndConquer/JU-CSE-MyLibrary#1]
# Problems:
1.There is a bit of white space on the right of the top bar
2.The height of the top bar is not persistant with the home page.

![screenshot_20190128-004248](https://user-images.githubusercontent.com/32241636/51805680-518acb00-2296-11e9-8a14-aa6eda484477.png)

**Comment by irinbanerjee** [comment]
Made changes..check
